substitutions:
  shelly_3em_url: "http://192.168.132.5/status/"

http_request:
  id: http_request0
  useragent: esphome/device
  timeout: 1000ms
  esp8266_disable_ssl_support: true

sensor:
  - platform: template
    id: powermeter0
    name: "Instantaneous Power"
    unit_of_measurement: W
    device_class: "power"
    accuracy_decimals: 2
    update_interval: never

interval:
  - interval: 1100ms
    then:
      - http_request.get:
          url: ${shelly_3em_url}
          headers:
            Content-Type: application/json
          capture_response: true
          max_response_buffer_size: 2000
          on_response:
            then:
              - lambda: |-
                  json::parse_json(body, [](JsonObject root) -> bool {
                    id(powermeter0).publish_state(root["total_power"]);
                    return true;
                  });
